# -*- coding: utf-8 -*-
"""Google-Cluster2Updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaP3GdKaq-rE-T-Mkk1tKRjjEL6D7YpH
"""

# Install required packages
!pip install -q kagglehub shap scikit-learn seaborn

#  Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import shap
import time
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    mean_squared_error, mean_absolute_error, r2_score,
    precision_score, recall_score, f1_score
)

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import plot_model

print("Imports done.")

#  Download dataset
path = kagglehub.dataset_download("derrickmwiti/google-2019-cluster-sample")
print("Dataset path:", path)

# Load data
data = pd.read_csv(f"{path}/borg_traces_data.csv")
print("Initial shape:", data.shape)
display(data.head())

# Basic info and cleaning like original
print("\nData info:")
display(data.info())

# Drop Unnamed: 0 if exists, select numeric, remove *_id columns, drop NA
if 'Unnamed: 0' in data.columns:
    data.drop('Unnamed: 0', axis=1, inplace=True)

# keep numeric columns only (like your original)
data = data.select_dtypes(exclude=['object'])
# remove any column that contains '_id' in name
data = data.loc[:, ~data.columns.str.contains('_id')]
# drop rows with missing values
data.dropna(inplace=True)
print("After dropping NA and id cols:", data.shape)

# Quick histograms (optional)
plt.figure(figsize=(14,8))
data.hist(figsize=(16,12))
plt.suptitle("Feature histograms")
plt.tight_layout()
plt.show()

#  Outlier winsorizing function (same approach you used)
def outlier_solver(DataFrame):
    df = DataFrame.copy()
    for i in df.columns:
        Q1 = df[i].quantile(0.25)
        Q3 = df[i].quantile(0.75)
        IQR = Q3 - Q1
        up_lim  = Q3 + 1.5 * IQR
        low_lim = Q1 - 1.5 * IQR
        df.loc[df[i] > up_lim, i]  = up_lim
        df.loc[df[i] < low_lim, i] = low_lim
    return df

data = outlier_solver(data)
print("After winsorizing outliers:", data.shape)

# Correlation heatmap
plt.figure(figsize=(12,10))
sns.heatmap(data.corr(), cmap='coolwarm', center=0)
plt.title("Correlation Heatmap")
plt.show()

# Drop specified columns if present
for col in ['collection_type','sample_rate']:
    if col in data.columns:
        data.drop(col, axis=1, inplace=True)
print("After dropping collection_type & sample_rate (if present):", data.shape)

#  EDA visuals
if 'cluster' in data.columns and 'failed' in data.columns:
    try:
        sns.countplot(data=data, x="cluster", hue="failed")
        plt.title("Countplot cluster vs failed")
        plt.show()
    except Exception as e:
        print("Countplot error (maybe many classes):", e)

    try:
        sns.barplot(data=data, x="cluster", y="time", hue="failed")
        plt.title("Time by cluster vs failed")
        plt.show()
    except Exception as e:
        print("Barplot error (maybe large classes):", e)

#  Prepare X and y
X = data.drop(['cluster','failed'], axis=1, inplace=False)
y_cat = keras.utils.to_categorical(data.loc[:,'cluster'])
print("X shape:", X.shape, "y (one-hot) shape:", y_cat.shape)

# Train/validation split as in original (90%-10%)
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y_cat, train_size=0.9, random_state=42, shuffle=True
)

# Scale features (important for NN)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)

input_shape  = [X.shape[1]]
output_shape = y_cat.shape[1]
print("Input shape:", input_shape, "Output shape (num classes):", output_shape)

# Build model
model = keras.Sequential([
    layers.BatchNormalization(input_shape=input_shape),

    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.15),

    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.25),

    layers.Dense(256, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.25),

    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.15),

    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.1),

    layers.Dense(output_shape, activation='softmax')
])

model.summary()

# Optionally visualize model (may require graphviz)
try:
    plot_model(model, show_shapes=True)
except:
    pass

# Compile and add callbacks: EarlyStopping + ModelCheckpoint
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

early_stopping = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=8, min_delta=0.001, restore_best_weights=True
)
checkpoint = keras.callbacks.ModelCheckpoint(
    'best_keras_model.h5', monitor='val_loss', save_best_only=True
)

# batch_size but fallback if OOM
requested_batch = 10000
batch_size = requested_batch
epochs = 50

# Try to fit, batch size if OOM or other memory issue
trained = False
try:
    history = model.fit(
        X_train, y_train,
        validation_data=(X_valid, y_valid),
        batch_size=batch_size,
        epochs=epochs,
        callbacks=[early_stopping, checkpoint],
        verbose=1
    )
    trained = True
except Exception as e:
    print(f"Training with batch_size={batch_size} failed: {e}")
    print("Retrying with batch_size=512")
    batch_size = 512
    history = model.fit(
        X_train, y_train,
        validation_data=(X_valid, y_valid),
        batch_size=batch_size,
        epochs=epochs,
        callbacks=[early_stopping, checkpoint],
        verbose=1
    )
    trained = True

# Plot training history
history_df = pd.DataFrame(history.history)
if 'loss' in history_df.columns:
    history_df[['loss','val_loss']].plot(title='Loss')
if 'accuracy' in history_df.columns:
    history_df[['accuracy','val_accuracy']].plot(title='Accuracy')
plt.show()

#  Load best model weights (ModelCheckpoint saved it) and evaluate
try:
    model.load_weights('best_keras_model.h5')
    print("Loaded best_keras_model.h5 weights.")
except Exception as e:
    print("Could not load checkpoint (maybe not saved). Using current weights.", e)

#  Predictions on validation set
y_pred_proba = model.predict(X_valid)
y_pred = np.argmax(y_pred_proba, axis=1)
y_true = np.argmax(y_valid, axis=1)

#  Metrics requested
precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)

# Regression-like metrics on class indices
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print("\n=== Evaluation Metrics ===")
print(f"RMSE (on class indices): {rmse:.4f}")
print(f"MAE  (on class indices): {mae:.4f}")
print(f"R^2  (on class indices): {r2:.4f}")
print(f"Precision (weighted): {precision:.4f}")
print(f"Recall    (weighted): {recall:.4f}")
print(f"F1-score  (weighted): {f1:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()

# Actual vs Predicted plot (class indices)
plt.figure(figsize=(12,5))
plt.scatter(range(len(y_true)), y_true, label='Actual', s=12)
plt.scatter(range(len(y_pred)), y_pred, label='Predicted', s=12, alpha=0.7)
plt.legend()
plt.title("Actual vs Predicted (cluster indices)")
plt.xlabel("Sample index")
plt.ylabel("Cluster ID")
plt.show()

plt.figure(figsize=(10, 6))
plt.scatter(y_true, y_pred, alpha=0.5)
plt.xlabel("Actual Cluster ID")
plt.ylabel("Predicted Cluster ID")
plt.title("Actual vs Predicted Cluster ID")
plt.grid(True)
plt.show()

# Manual ICE-like plot for one feature
# Pick a feature index to analyze (0 = first feature). You can change this index.
feature_idx = 0
feature_name = X.columns[feature_idx]

# Use a copy of validation features (not scaled back) - but our X_valid is scaled; it's fine to use scaled values
X_valid_copy = X_valid.copy()
n_points = 25
vals = np.linspace(np.percentile(X_valid_copy[:, feature_idx], 5),
                   np.percentile(X_valid_copy[:, feature_idx], 95), n_points)

avg_top_probs = []
for v in vals:
    X_temp = X_valid_copy.copy()
    X_temp[:, feature_idx] = v
    probs = model.predict(X_temp, verbose=0)
    top_prob = probs.max(axis=1)  # per-sample top-class prob
    avg_top_probs.append(top_prob.mean())

plt.figure(figsize=(8,5))
plt.plot(vals, avg_top_probs, marker='o')
plt.xlabel(f"{feature_name} (scaled value)")
plt.ylabel("Average top-class probability")
plt.title(f"ICE-like plot for feature: {feature_name}")
plt.grid(True)
plt.show()

# SHAP explanation (small sample)
# NOTE: DeepExplainer + Keras can be heavy. We use a small subset to avoid memory issues.
try:
    print("\nRunning SHAP (this may take time). Using small subsets...")
    small_train = X_train[:200] if X_train.shape[0] > 200 else X_train
    small_valid = X_valid[:200] if X_valid.shape[0] > 200 else X_valid

    # Use GradientExplainer or DeepExplainer depending on TF version - try DeepExplainer
    explainer = shap.DeepExplainer(model, small_train)
    shap_values = explainer.shap_values(small_valid)

    # shap_values is a list per class; create a summary_plot for all classes combined by summing magnitude
    # For multi-class, shap.summary_plot accepts list-of-arrays; it will plot per-class separately unless aggregated.
    shap.summary_plot(shap_values, small_valid, feature_names=X.columns)
except Exception as e:
    print("SHAP failed or was too heavy on this environment:", e)

print("\nNotebook run complete.")

import matplotlib.pyplot as plt

y_pred_probs = model.predict(X_valid)
y_pred_classes = np.argmax(y_pred_probs, axis=1)

# Convert y_valid from one-hot encoding to class indices
y_valid_classes = np.argmax(y_valid, axis=1)


plt.figure(figsize=(7,6))

# Plot neural net
plt.scatter(y_valid_classes, y_pred_classes, alpha=0.7, label="Neural Net (best single model)", color="green")

# Perfect prediction line
plt.plot([y_valid_classes.min(), y_valid_classes.max()], [y_valid_classes.min(), y_valid_classes.max()], 'r--', label="Perfect Prediction")

plt.xlabel("Actual Cluster ID", fontsize=12)
plt.ylabel("Predicted Cluster ID", fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()